
package cn.mw.monitor.weixin.mypackage;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SMSServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SMSServiceSoap {


    /**
     * �������
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TestService", action = "http://tempuri.org/TestService")
    @WebResult(name = "TestServiceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TestService", targetNamespace = "http://tempuri.org/", className = "mypackage.TestService")
    @ResponseWrapper(localName = "TestServiceResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.TestServiceResponse")
    public String testService();

    /**
     * ��������
     * 
     * @param appSMSCode
     * @param bizTypeID
     * @param isNeedReport
     * @param extNo
     * @param appID
     * @param appPWD
     * @param bizClassID
     * @param custID
     * @param bizSubTypeID
     * @param phoneNo
     * @param content
     * @return
     *     returns mypackage.SendSMSRet
     */
    @WebMethod(operationName = "SendSMS", action = "http://tempuri.org/SendSMS")
    @WebResult(name = "SendSMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://tempuri.org/", className = "mypackage.SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.SendSMSResponse")
    public SendSMSRet sendSMS(
            @WebParam(name = "App_ID", targetNamespace = "http://tempuri.org/")
                    int appID,
            @WebParam(name = "App_PWD", targetNamespace = "http://tempuri.org/")
                    String appPWD,
            @WebParam(name = "Biz_Class_ID", targetNamespace = "http://tempuri.org/")
                    String bizClassID,
            @WebParam(name = "Biz_Type_ID", targetNamespace = "http://tempuri.org/")
                    String bizTypeID,
            @WebParam(name = "Biz_Sub_Type_ID", targetNamespace = "http://tempuri.org/")
                    String bizSubTypeID,
            @WebParam(name = "Ext_No", targetNamespace = "http://tempuri.org/")
                    String extNo,
            @WebParam(name = "Phone_No", targetNamespace = "http://tempuri.org/")
                    String phoneNo,
            @WebParam(name = "Content", targetNamespace = "http://tempuri.org/")
                    String content,
            @WebParam(name = "Is_Need_Report", targetNamespace = "http://tempuri.org/")
                    int isNeedReport,
            @WebParam(name = "Cust_ID", targetNamespace = "http://tempuri.org/")
                    BigDecimal custID,
            @WebParam(name = "App_SMS_Code", targetNamespace = "http://tempuri.org/")
                    String appSMSCode);

    /**
     * ��������
     *
     * @param bizTypeID
     * @param isNeedReport
     * @param extNo
     * @param appID
     * @param appPWD
     * @param bizClassID
     * @param infoList
     * @param bizSubTypeID
     * @param isEnd
     * @param taskID
     * @return
     *     returns mypackage.SendSMSListRet
     */
    @WebMethod(operationName = "SendSMSList", action = "http://tempuri.org/SendSMSList")
    @WebResult(name = "SendSMSListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSMSList", targetNamespace = "http://tempuri.org/", className = "mypackage.SendSMSList")
    @ResponseWrapper(localName = "SendSMSListResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.SendSMSListResponse")
    public SendSMSListRet sendSMSList(
            @WebParam(name = "App_ID", targetNamespace = "http://tempuri.org/")
                    int appID,
            @WebParam(name = "App_PWD", targetNamespace = "http://tempuri.org/")
                    String appPWD,
            @WebParam(name = "Task_ID", targetNamespace = "http://tempuri.org/")
                    String taskID,
            @WebParam(name = "Biz_Class_ID", targetNamespace = "http://tempuri.org/")
                    String bizClassID,
            @WebParam(name = "Biz_Type_ID", targetNamespace = "http://tempuri.org/")
                    String bizTypeID,
            @WebParam(name = "Biz_Sub_Type_ID", targetNamespace = "http://tempuri.org/")
                    String bizSubTypeID,
            @WebParam(name = "Ext_No", targetNamespace = "http://tempuri.org/")
                    String extNo,
            @WebParam(name = "Info_List", targetNamespace = "http://tempuri.org/")
                    ArrayOfSendInfo infoList,
            @WebParam(name = "Is_Need_Report", targetNamespace = "http://tempuri.org/")
                    int isNeedReport,
            @WebParam(name = "Is_End", targetNamespace = "http://tempuri.org/")
                    int isEnd);

    /**
     * ��������
     *
     * @param preorderMode
     * @param isNeedReport
     * @param priority
     * @param autoMode
     * @param periodicMode
     * @param bizTypeID
     * @param taskContent
     * @param appID
     * @param appPWD
     * @param bizClassID
     * @param scheduleMode
     * @param taskName
     * @param startTime
     * @param stopTime
     * @param timeSchemeID
     * @param bizSubTypeID
     * @return
     *     returns mypackage.SendSMSRet
     */
    @WebMethod(operationName = "CreatTask", action = "http://tempuri.org/CreatTask")
    @WebResult(name = "CreatTaskResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreatTask", targetNamespace = "http://tempuri.org/", className = "mypackage.CreatTask")
    @ResponseWrapper(localName = "CreatTaskResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.CreatTaskResponse")
    public SendSMSRet creatTask(
            @WebParam(name = "App_ID", targetNamespace = "http://tempuri.org/")
                    int appID,
            @WebParam(name = "App_PWD", targetNamespace = "http://tempuri.org/")
                    String appPWD,
            @WebParam(name = "Task_Name", targetNamespace = "http://tempuri.org/")
                    String taskName,
            @WebParam(name = "Biz_Class_ID", targetNamespace = "http://tempuri.org/")
                    String bizClassID,
            @WebParam(name = "Biz_Type_ID", targetNamespace = "http://tempuri.org/")
                    String bizTypeID,
            @WebParam(name = "Biz_Sub_Type_ID", targetNamespace = "http://tempuri.org/")
                    String bizSubTypeID,
            @WebParam(name = "StartTime", targetNamespace = "http://tempuri.org/")
                    XMLGregorianCalendar startTime,
            @WebParam(name = "Stop_Time", targetNamespace = "http://tempuri.org/")
                    XMLGregorianCalendar stopTime,
            @WebParam(name = "Priority", targetNamespace = "http://tempuri.org/")
                    int priority,
            @WebParam(name = "Is_Need_Report", targetNamespace = "http://tempuri.org/")
                    int isNeedReport,
            @WebParam(name = "Task_Content", targetNamespace = "http://tempuri.org/")
                    String taskContent,
            @WebParam(name = "Time_Scheme_ID", targetNamespace = "http://tempuri.org/")
                    int timeSchemeID,
            @WebParam(name = "Auto_Mode", targetNamespace = "http://tempuri.org/")
                    int autoMode,
            @WebParam(name = "Preorder_Mode", targetNamespace = "http://tempuri.org/")
                    int preorderMode,
            @WebParam(name = "Schedule_Mode", targetNamespace = "http://tempuri.org/")
                    int scheduleMode,
            @WebParam(name = "Periodic_Mode", targetNamespace = "http://tempuri.org/")
                    int periodicMode);

    /**
     * ��ѯ���ͽ��/��ִ(����)
     *
     * @param smsID
     * @param appID
     * @param appPWD
     * @return
     *     returns mypackage.ReportResponse
     */
    @WebMethod(operationName = "GetReportResponse", action = "http://tempuri.org/GetReportResponse")
    @WebResult(name = "GetReportResponseResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetReportResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.GetReportResponse")
    @ResponseWrapper(localName = "GetReportResponseResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.GetReportResponseResponse")
    public ReportResponse getReportResponse(
            @WebParam(name = "App_ID", targetNamespace = "http://tempuri.org/")
                    int appID,
            @WebParam(name = "App_PWD", targetNamespace = "http://tempuri.org/")
                    String appPWD,
            @WebParam(name = "SMS_ID", targetNamespace = "http://tempuri.org/")
                    String smsID);

    /**
     * ��ѯ���ͽ��/��ִ(����),���Զ�ε���
     *
     * @param appID
     * @param appPWD
     * @param taskID
     * @return
     *     returns mypackage.ReportResponse
     */
    @WebMethod(operationName = "GetReportListResponse", action = "http://tempuri.org/GetReportListResponse")
    @WebResult(name = "GetReportListResponseResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetReportListResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.GetReportListResponse")
    @ResponseWrapper(localName = "GetReportListResponseResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.GetReportListResponseResponse")
    public ReportResponse getReportListResponse(
            @WebParam(name = "App_ID", targetNamespace = "http://tempuri.org/")
                    int appID,
            @WebParam(name = "App_PWD", targetNamespace = "http://tempuri.org/")
                    String appPWD,
            @WebParam(name = "Task_ID", targetNamespace = "http://tempuri.org/")
                    String taskID);

    /**
     * ��ѯ����������Ϣ
     *
     * @param appID
     * @param appPWD
     * @param taskID
     * @return
     *     returns mypackage.TaskInfoResponse
     */
    @WebMethod(operationName = "GetTaskInfo", action = "http://tempuri.org/GetTaskInfo")
    @WebResult(name = "GetTaskInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTaskInfo", targetNamespace = "http://tempuri.org/", className = "mypackage.GetTaskInfo")
    @ResponseWrapper(localName = "GetTaskInfoResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.GetTaskInfoResponse")
    public TaskInfoResponse getTaskInfo(
            @WebParam(name = "App_ID", targetNamespace = "http://tempuri.org/")
                    int appID,
            @WebParam(name = "App_PWD", targetNamespace = "http://tempuri.org/")
                    String appPWD,
            @WebParam(name = "Task_ID", targetNamespace = "http://tempuri.org/")
                    String taskID);

    /**
     * ��ѯ�ظ�/��ִ/����״̬��ÿ�η���100��ͬһ�ظ������ظ�����
     *
     * @param appID
     * @param appPWD
     * @return
     *     returns mypackage.ReceveResponse
     */
    @WebMethod(operationName = "GetReceveInfo", action = "http://tempuri.org/GetReceveInfo")
    @WebResult(name = "GetReceveInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetReceveInfo", targetNamespace = "http://tempuri.org/", className = "mypackage.GetReceveInfo")
    @ResponseWrapper(localName = "GetReceveInfoResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.GetReceveInfoResponse")
    public ReceveResponse getReceveInfo(
            @WebParam(name = "App_ID", targetNamespace = "http://tempuri.org/")
                    int appID,
            @WebParam(name = "App_PWD", targetNamespace = "http://tempuri.org/")
                    String appPWD);

    /**
     * ��ѯ����״̬�����б�
     * 
     * @return
     *     returns mypackage.SMSStatusReponse
     */
    @WebMethod(operationName = "GetSMS_Status_Info", action = "http://tempuri.org/GetSMS_Status_Info")
    @WebResult(name = "GetSMS_Status_InfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSMS_Status_Info", targetNamespace = "http://tempuri.org/", className = "mypackage.GetSMSStatusInfo")
    @ResponseWrapper(localName = "GetSMS_Status_InfoResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.GetSMSStatusInfoResponse")
    public SMSStatusReponse getSMSStatusInfo();

}
