
package cn.mw.monitor.weixin.mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SMSService", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/C:/Users/dev.quaee/Desktop/\u77ed\u4fe1\u5e73\u53f0Web Service\u63a5\u53e3\u8bf4\u660e/smsservice.wsdl")
public class SMSService
    extends Service
{

    private final static URL SMSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SMSSERVICE_EXCEPTION;
    private final static QName SMSSERVICE_QNAME = new QName("http://tempuri.org/", "SMSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/dev.quaee/Desktop/\u77ed\u4fe1\u5e73\u53f0Web Service\u63a5\u53e3\u8bf4\u660e/smsservice.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMSSERVICE_WSDL_LOCATION = url;
        SMSSERVICE_EXCEPTION = e;
    }

    public SMSService() {
        super(__getWsdlLocation(), SMSSERVICE_QNAME);
    }

    public SMSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMSSERVICE_QNAME, features);
    }

    public SMSService(URL wsdlLocation) {
        super(wsdlLocation, SMSSERVICE_QNAME);
    }

    public SMSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMSSERVICE_QNAME, features);
    }

    public SMSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SMSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SMSServiceSoap
     */
    @WebEndpoint(name = "SMSServiceSoap")
    public SMSServiceSoap getSMSServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "SMSServiceSoap"), SMSServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SMSServiceSoap
     */
    @WebEndpoint(name = "SMSServiceSoap")
    public SMSServiceSoap getSMSServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SMSServiceSoap"), SMSServiceSoap.class, features);
    }

    /**
     *
     * @return
     *     returns SMSServiceSoap
     */
    @WebEndpoint(name = "SMSServiceSoap12")
    public SMSServiceSoap getSMSServiceSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "SMSServiceSoap12"), SMSServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SMSServiceSoap
     */
    @WebEndpoint(name = "SMSServiceSoap12")
    public SMSServiceSoap getSMSServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SMSServiceSoap12"), SMSServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMSSERVICE_EXCEPTION!= null) {
            throw SMSSERVICE_EXCEPTION;
        }
        return SMSSERVICE_WSDL_LOCATION;
    }

}
