package cn.mw.monitor.server.serverdto;

import java.util.List;

/**
 * @author syt
 * @Date 2021/1/5 15:09
 * @Version 1.0
 */
public enum InterfaceInfoEnum {
    MW_INTERFACE_NAME("MW_INTERFACE_NAME"),
    MW_INTERFACE_OUT_TRAFFIC("MW_INTERFACE_OUT_TRAFFIC"),
    INTERFACE_OUT_PACKETS("INTERFACE_OUT_PACKETS"),
    INTERFACE_OUT_ERRORS("INTERFACE_OUT_ERRORS"),
    INTERFACE_OUT_DROP_RATE("INTERFACE_OUT_DROP_RATE"),
    MW_INTERFACE_OUT_DROPPED("MW_INTERFACE_OUT_DROPPED"),
    MW_INTERFACE_IN_TRAFFIC("MW_INTERFACE_IN_TRAFFIC"),
    INTERFACE_IN_PACKETS("INTERFACE_IN_PACKETS"),
    INTERFACE_IN_ERRORS("INTERFACE_IN_ERRORS"),
    INTERFACE_IN_DROP_RATE("INTERFACE_IN_DROP_RATE"),
    MW_INTERFACE_IN_DROPPED("MW_INTERFACE_IN_DROPPED"),
    INTERFACE_IN_BROADCAST_PACKETS("INTERFACE_IN_BROADCAST_PACKETS"),
    INTERFACE_IN_UNICAST_PACKETS("INTERFACE_IN_UNICAST_PACKETS"),
    INTERFACE_IN_UTILIZATION("INTERFACE_IN_UTILIZATION"),
    INTERFACE_OUT_UTILIZATION("INTERFACE_OUT_UTILIZATION"),
    INTERFACE_OUT_BROADCAST_PACKETS("INTERFACE_OUT_BROADCAST_PACKETS"),
    INTERFACE_OUT_UNICAST_PACKETS("INTERFACE_OUT_UNICAST_PACKETS"),
    INTERFACE_IN_TOTALTRAFFIC("INTERFACE_IN_TOTALTRAFFIC"),
    INTERFACE_OUT_TOTALTRAFFIC("INTERFACE_OUT_TOTALTRAFFIC"),
    MW_INTERFACE_SPEED("MW_INTERFACE_SPEED"),
    INTERFACE_ADMINSTATUS("INTERFACE_ADMINSTATUS"),
    MW_INTERFACE_STATUS("MW_INTERFACE_STATUS"),
    INTERFACE_DESCR("INTERFACE_DESCR"),
    INTERFACE_BANDWIDTH("INTERFACE_BANDWIDTH"),
    INTERFACE_MTU("INTERFACE_MTU"),
    INTERFACE_INDEX("INTERFACE_INDEX"),
    INTERFACE_MACADDR("INTERFACE_MACADDR"),
    INTERFACE_DuplexStatus("INTERFACE_DuplexStatus");

    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    InterfaceInfoEnum(String name) {
        this.name = name;
    }
}
